cmake_minimum_required(VERSION 3.5)

set(SOURCES 
src/platforms/esp32/main/main.c
src/platforms/esp32/main/platform.c
src/platforms/esp32/main/gdb_if.c
src/platforms/esp32/main/rtt_if.c
src/platforms/esp32/main/swo_if.c
src/platforms/esp32/main/swo_uart.c
src/platforms/esp32/main/spi_fpga.c
src/platforms/esp32/main/spi2swd.c
src/platforms/esp32/main/spi2jtag.c
src/command.c
src/crc32.c
src/exception.c
src/gdb_main.c
src/gdb_packet.c
src/hex_utils.c
src/main.c
src/maths_utils.c
src/morse.c
src/remote.c
src/timing.c
src/rtt.c
src/target/adi.c
src/target/adiv5.c
src/target/adiv5_jtag.c
src/target/adiv5_swd.c
src/target/adiv6.c
src/target/gdb_reg.c
src/target/jtag_devs.c
src/target/jtag_scan.c
src/target/semihosting.c
src/target/sfdp.c
src/target/spi.c
src/target/target.c
src/target/target_flash.c
src/target/target_probe.c
src/target/cortexar.c
src/target/cortex.c
src/target/cortexm.c
src/target/riscv32.c
src/target/riscv_debug.c
src/target/riscv_adi_dtm.c
src/target/riscv_jtag_dtm.c
src/target/riscv64.c
src/target/apollo3.c
src/target/at32f43x.c
src/target/stm32_common.c
src/target/ch32f1.c
src/target/stm32f1.c
src/target/ch579.c
src/target/efm32.c
src/target/stm32f4.c
src/target/hc32l110.c
src/target/lpc11xx.c
src/target/lpc15xx.c
src/target/lpc17xx.c
src/target/lpc40xx.c
src/target/lpc43xx.c
src/target/lpc546xx.c
src/target/lpc55xx.c
src/target/lpc_common.c
src/target/nrf51.c
src/target/nrf54l.c
src/target/nrf91.c
src/target/imxrt.c
src/target/kinetis.c
src/target/nxpke04.c
src/target/s32k3xx.c
src/target/puya.c
src/target/renesas_ra.c
src/target/renesas_rz.c
src/target/rp2040.c
src/target/rp2350.c
src/target/sam3x.c
src/target/sam4l.c
src/target/samd.c
src/target/samx5x.c
src/target/stm32g0.c
src/target/stm32h5.c
src/target/stm32h7.c
src/target/stm32l0.c
src/target/stm32l4.c
src/target/stm32mp15.c
src/target/stm32wb0.c
src/target/lmi.c
src/target/msp432e4.c
src/target/msp432p4.c
src/target/mspm0.c
src/target/zynq7000.c
)

set(TARGETS 
)

idf_component_register(
        SRCS ${SOURCES} ${TARGETS}
        INCLUDE_DIRS 
            ./src/include
            ./src/platforms/common
            ./src/target
            ./src/platforms/esp32/main
        REQUIRES driver esp_event esp_wifi nvs_flash esp_timer platform_include
)

target_compile_definitions(${COMPONENT_TARGET}
    PRIVATE
        NO_LIBOPENCM3=1
        CONFIG_BMDA=0
        HOSTED_BMP_ONLY=1
        ENABLE_RTT=1        
        PLATFORM_HAS_TRACESWO=1
        SWO_ENCODING=2
)
